name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check Commit Message [skip CI]
        env:
          COMMIT_FILTER: "[skip ci]"
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: |
          echo "no 'skip ci' in commit message"
          exit 2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: base64-to-file
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
        with:
          fileName: 'key.jks'
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
        run: |
          touch keystore.properties
          echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> keystore.properties
          echo keyAlias='${{ secrets.ALIAS }}' >> keystore.properties
          echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
          echo storeFile='${{ steps.write_file.outputs.filePath }}' >> keystore.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            gradle-deps

      - name: Build with Gradle
        run: |
          [ $(du -s ~/.gradle/wrapper | awk '{ print $1 }') -gt 250000 ] && rm -rf ~/.gradle/wrapper/* || true
           chmod +x gradlew
           ./gradlew assembleRelease

      - name: Upload assets to a Release
        uses: meeDamian/github-release@v2.0.3
        with:
          files: app/build/outputs/apk/release/*.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          allow_override: true
          gzip: false